services:
  app:
    build: .
    container_name: swift-service
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb+srv://kamilkoscielny2002:Qetuoadgjlxvn.1@cluster0.wpmnnvs.mongodb.net/
    volumes:
      - ./secrets/credentials.json:/app/secrets/credentials.json
      - ./Data.csv:/root/Data.csv
    networks:
      - swift-net

volumes:
  mongo-data:

networks:
  swift-net:
    driver: bridge